In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Height-Weight Data.csv')

In [3]:
df.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [5]:
df.describe()

Height       Weight
count  3501.000000  3501.000000
mean     69.024411   186.891258
std       2.858583    19.903132
min      59.380650    65.780000
25%      67.193523   173.896237
50%      69.044211   187.308370
75%      70.976491   200.356448
max      78.998742   269.989698

In [6]:
x = df[['Height']]  # x = df.drop('rent', axis=1) # ind var
y = df['Weight'] #dep variable

In [7]:
df.head(10)

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801
5  67.253016  152.212156
6  68.785081  183.927889
7  68.348516  167.971111
8  67.018950  175.929440
9  63.456494  156.399676

In [8]:
from sklearn.model_selection import train_test_split as tts

In [9]:
xtrain , xtest , ytrain, ytest = tts(x,y,train_size=.70,random_state=1) #test_size=.30
#train, test = tts(df,train_size=.70,random_state=1) #test_size=.30

In [10]:
xtrain.shape

(2450, 1)

In [11]:
xtrain.head() #52, 17

Height
221   66.786927
2696  65.192862
1334  68.390109
3402  68.145621
1159  71.647580

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
lr = LinearRegression() # creating object for linear model

In [14]:
lr.fit(xtrain ,ytrain) #train the ML model ; xtrain=x ; ytrain=y

LinearRegression()

In [15]:
lr.coef_

array([5.97744946])

In [16]:
lr.intercept_

-225.82603000755844

In [17]:
m = lr.coef_
c = lr.intercept_

In [18]:
x = 70
y = (m * x) + c

In [19]:
y

array([192.59543231])

In [20]:
df

Height      Weight
0     73.847017  241.893563
1     68.781904  162.310473
2     74.110105  212.740856
3     71.730978  220.042470
4     69.881796  206.349801
...         ...         ...
3496  69.296830  185.649086
3497  70.542201  210.198845
3498  73.912549  202.429960
3499  67.396021  144.277671
3500  72.738970  187.222909

[3501 rows x 2 columns]

In [22]:
lr.predict(df[['Height']])

array([215.59078213, 185.31432533, 217.16337956, ..., 215.98249712,
       177.03027812, 208.96748706])

In [23]:
df['Predicted Weight'] = lr.predict(df[['Height']]) # y=mx+c

In [24]:
df.head()

Height      Weight  Predicted Weight
0  73.847017  241.893563        215.590782
1  68.781904  162.310473        185.314325
2  74.110105  212.740856        217.163380
3  71.730978  220.042470        202.942268
4  69.881796  206.349801        191.888873

In [25]:
from sklearn.metrics import mean_absolute_error

In [30]:
from sklearn.metrics import mean_squared_error # mse
pred = lr.predict(xtest)
mse = mean_squared_error(ytest , pred) #testing error

In [31]:
mse

110.89221516932378

In [32]:
lr.score(xtest, ytest) # R Squared Value

0.7313258168853622

In [33]:
lr.score(xtrain, ytrain) # R Squared Value

0.7327243206606744